/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppApuracaoRouteImport } from './routes/_app/apuracao'
import { Route as AppEstadosRouteImport } from './routes/_app/estados'
import { Route as AppIndicadoresRouteImport } from './routes/_app/indicadores'
import { Route as AppRegioesRouteImport } from './routes/_app/regioes'
import { Route as AppSobreRouteImport } from './routes/_app/sobre'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApuracaoRoute = AppApuracaoRouteImport.update({
  id: '/apuracao',
  path: '/apuracao',
  getParentRoute: () => AppRoute,
} as any)
const AppEstadosRoute = AppEstadosRouteImport.update({
  id: '/estados',
  path: '/estados',
  getParentRoute: () => AppRoute,
} as any)
const AppIndicadoresRoute = AppIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => AppRoute,
} as any)
const AppRegioesRoute = AppRegioesRouteImport.update({
  id: '/regioes',
  path: '/regioes',
  getParentRoute: () => AppRoute,
} as any)
const AppSobreRoute = AppSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/apuracao': typeof AppApuracaoRoute
  '/estados': typeof AppEstadosRoute
  '/indicadores': typeof AppIndicadoresRoute
  '/regioes': typeof AppRegioesRoute
  '/sobre': typeof AppSobreRoute
}
export interface FileRoutesByTo {
  '/apuracao': typeof AppApuracaoRoute
  '/estados': typeof AppEstadosRoute
  '/indicadores': typeof AppIndicadoresRoute
  '/regioes': typeof AppRegioesRoute
  '/sobre': typeof AppSobreRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/apuracao': typeof AppApuracaoRoute
  '/_app/estados': typeof AppEstadosRoute
  '/_app/indicadores': typeof AppIndicadoresRoute
  '/_app/regioes': typeof AppRegioesRoute
  '/_app/sobre': typeof AppSobreRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/apuracao' | '/estados' | '/indicadores' | '/regioes' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/apuracao' | '/estados' | '/indicadores' | '/regioes' | '/sobre' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/apuracao'
    | '/_app/estados'
    | '/_app/indicadores'
    | '/_app/regioes'
    | '/_app/sobre'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apuracao': {
      id: '/_app/apuracao'
      path: '/apuracao'
      fullPath: '/apuracao'
      preLoaderRoute: typeof AppApuracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estados': {
      id: '/_app/estados'
      path: '/estados'
      fullPath: '/estados'
      preLoaderRoute: typeof AppEstadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/indicadores': {
      id: '/_app/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AppIndicadoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/regioes': {
      id: '/_app/regioes'
      path: '/regioes'
      fullPath: '/regioes'
      preLoaderRoute: typeof AppRegioesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sobre': {
      id: '/_app/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof AppSobreRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApuracaoRoute: typeof AppApuracaoRoute
  AppEstadosRoute: typeof AppEstadosRoute
  AppIndicadoresRoute: typeof AppIndicadoresRoute
  AppRegioesRoute: typeof AppRegioesRoute
  AppSobreRoute: typeof AppSobreRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApuracaoRoute: AppApuracaoRoute,
  AppEstadosRoute: AppEstadosRoute,
  AppIndicadoresRoute: AppIndicadoresRoute,
  AppRegioesRoute: AppRegioesRoute,
  AppSobreRoute: AppSobreRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
